// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddScanPath(arg1:string):Promise<main.Settings>;

export function DeleteProject(arg1:string):Promise<boolean>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetSettings():Promise<main.Settings>;

export function OpenInEditor(arg1:string,arg2:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function RefreshProject(arg1:string):Promise<main.Project>;

export function RemoveScanPath(arg1:string):Promise<main.Settings>;

export function SelectFolder():Promise<string>;

export function SyncProjects():Promise<Array<main.Project>>;

export function UpdateProject(arg1:string,arg2:{[key: string]: any}):Promise<main.Project>;
