// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScanPath(arg1) {
  return window['go']['main']['App']['AddScanPath'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditor'](arg1, arg2);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OpenInTerminal(arg1) {
  return window['go']['main']['App']['OpenInTerminal'](arg1);
}

export function RefreshProject(arg1) {
  return window['go']['main']['App']['RefreshProject'](arg1);
}

export function RemoveScanPath(arg1) {
  return window['go']['main']['App']['RemoveScanPath'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SyncProjects() {
  return window['go']['main']['App']['SyncProjects']();
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}
